import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="invisible h-2 w-full bg-primary sm:visible"></div>
        <header className="top-0 w-full">
        <nav className="flex h-16 max-w-7xl items-center justify-between gap-x-6 p-6 lg:px-8">
          <a href="/">
            <h1 className="relative flex select-none flex-row items-baseline font-bold text-4xl">
              ssl
              <span className="text-primary">
                station
              </span>
            </h1>
          </a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
